apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      name: conv-api
      labels:
        components: backend
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 500Mi
              cpu: 200m
          env:
            - name: {{ .Values.api.env }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.name }}-secret
                  key: {{ .Values.api.env }}
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - "http://localhost:{{ .Values.api.port }}/api"
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
          startupProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: test
          configMap:
            name: demo-config
