apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rabbitmq
  template:
    metadata:
      labels:
        components: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12
          ports:
            - containerPort: 5672
          env:
            - name: SEED_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: SEED_USERNAME
            - name: SEED_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: SEED_USER_PASSWORD
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_PASSWORD
            # todo: - name: AMQP_HOSTNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: rabbitmq-secret
            #       key: AMQP_HOSTNAME
            - name: AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_QUEUE
          resources:
            limits:
              memory: 512Mi
              cpu: 300m
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
              # subPath: rabbitmq
            - name: rabbitmq-images
              mountPath: /opt/app/volumes
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
