apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
type: Opaque
data:
  DATABASE_URL: {{ with .Values.database }}{{ printf "amqp://%s:%s@%s:%d/%s" .user .password .host (.port | int64) .queue | b64enc | quote }}{{ end }}
