apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    {{- include 'chart.labels' . | nindent 4}}
data:
  name: {{ .Values.app.version | upper | quote }}
  {{- if eq .Values.env 'production' }}
  paymentToken: '1234'
  {{- else }}
  paymentToken: false
  {{- end }}
  {{- with .Values.value.requirements.limits}}
  cpu: {{ .cpu }}
  memory: {{ .memory }}
  version: {{ $.Release.name }}
  {{- end }}
  {{- $map := .Release.Name | upper | quote }}
  map: {{ $map }}
  user: |-
    {{- range tuple 'Michael' 'Vasya' }}
    - {{ . }}
    {{- end }}
